workflows:
  kivy-android:
    name: Build Kivy APK
    environment:
      vars:
        BUILD_TYPE: "debug"
    scripts:
      - name: Install dependencies
        script: |
          sudo apt-get update -qq
          sudo apt-get install -y build-essential git zip unzip openjdk-17-jdk python3-pip \
            autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev \
            libtinfo5 cmake
          pip install --upgrade pip wheel Cython buildozer
      - name: Build APK
        script: |
          cd $CM_BUILD_DIR
          if [ ! -f buildozer.spec ]; then buildozer init; fi
          buildozer -v android debug
    artifacts:
      - build/*.apk
