workflows:
  kivy-android:
    name: Build Kivy APK
    environment:
      vars:
        BUILD_TYPE: "debug"
      python: 3.10
    scripts:
      - name: Install dependencies
        script: |
          brew install autoconf automake libtool pkg-config cmake
          python3 -m pip install --upgrade pip wheel Cython setuptools
          python3 -m pip install buildozer
          python3 -m pip install setuptools==65.5.0
          python3 -m pip install distutils-py
      - name: Build APK
        script: |
          cd $CM_BUILD_DIR
          if [ ! -f buildozer.spec ]; then buildozer init; fi
          buildozer -v android debug
    artifacts:
      - build/*.apk
