name: Build Kivy APK

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          build-essential \
          git \
          zip \
          unzip \
          openjdk-11-jdk \
          python3 \
          python3-pip \
          python3-setuptools \
          python3-venv \
          libffi-dev \
          libssl-dev \
          liblzma-dev \
          libjpeg-dev \
          zlib1g-dev \
          libncurses5

    - name: Install buildozer
      run: |
        pip3 install --upgrade pip setuptools wheel Cython
        pip3 install buildozer

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app
        path: bin/*.apk
