name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt update -qq
        sudo apt install -y \
          build-essential \
          git \
          openjdk-17-jdk \
          unzip \
          zlib1g-dev \
          libncurses5 \
          libncurses5-dev \
          libtinfo5 \
          libffi-dev \
          libssl-dev \
          autoconf \
          libtool \
          pkg-config \
          cmake

    - name: Install Python deps
      run: |
        python -m pip install --upgrade pip wheel Cython buildozer

    - name: Install Android SDK & Build Tools
      run: |
        yes | sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager --licenses
        sudo ${ANDROID_HOME}/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      run: |
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk

