name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          sudo apt-get update -y
          sudo apt-get install -y \
            openjdk-17-jdk \
            ant \
            unzip \
            wget \
            git \
            libffi-dev \
            libssl-dev \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5 \
            libncurses5-dev \
            libtinfo5 \
            cmake \
            build-essential
          python3 -m pip install --upgrade pip wheel Cython buildozer

      - name: Install Android SDK
        run: |
          mkdir -p $HOME/android-sdk
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
          unzip cmdline-tools.zip -d $HOME/android-sdk/
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          mv $HOME/android-sdk/cmdline-tools/* $HOME/android-sdk/cmdline-tools/latest/ || true
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager --licenses
          yes | $HOME/android-sdk/cmdline-tools/latest/bin/sdkmanager \
            "platform-tools" "platforms;android-35" "build-tools;35.0.0" "ndk;25.2.9519653"

      - name: Build APK
        run: |
          export ANDROIDSDK=$HOME/android-sdk
          export ANDROIDNDK=$HOME/android-sdk/ndk/25.2.9519653
          export ANDROIDAPI=35
          export ANDROIDMINAPI=24
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AABauservice-APK
          path: bin/*.apk
