name: Build Kivy APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            build-essential git zip unzip openjdk-17-jdk \
            python3 python3-pip python3-setuptools python3-wheel \
            autoconf libtool pkg-config zlib1g-dev \
            libncurses5 libncurses5-dev libtinfo5 \
            cmake libffi-dev libssl-dev libsqlite3-dev \
            libjpeg-dev libfreetype6-dev libblas-dev liblapack-dev gfortran

      - name: Install Buildozer
        run: |
          pip install --upgrade pip wheel Cython buildozer

      - name: Build APK
        run: |
          export ANDROIDSDK=$HOME/.buildozer/android/platform/android-sdk
          export ANDROIDNDK=$HOME/.buildozer/android/platform/android-ndk-r25b
          export ANDROIDAPI=31
          export ANDROIDMINAPI=24
          buildozer android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: AABauservice-APK
          path: bin/*.apk
