name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3-pip zip unzip openjdk-17-jdk libffi-dev libssl-dev autoconf automake libtool pkg-config zlib1g-dev

      - name: Install buildozer
        run: |
          pip3 install --upgrade pip setuptools wheel Cython
          pip3 install buildozer==1.5.0

      - name: Configure Android NDK/SDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform
          # Android NDK r21e (stabilna wersja dla Buildozer)
          wget https://dl.google.com/android/repository/android-ndk-r21e-linux-x86_64.zip
          unzip -q android-ndk-r21e-linux-x86_64.zip
          mv android-ndk-r21e ndk-r21e
          rm android-ndk-r21e-linux-x86_64.zip

      - name: Build APK
        run: |
          buildozer android debug log_level=2

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: kivy-apk
          path: bin/*.apk
