name: Build Kivy APK

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip python3-setuptools python3-wheel \
            git zip unzip openjdk-17-jdk libffi-dev libssl-dev \
            libsqlite3-dev zlib1g-dev

      - name: Install buildozer
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer==1.5.0

      - name: Configure Android SDK/NDK
        run: |
          mkdir -p $HOME/.buildozer/android/platform
          cd $HOME/.buildozer/android/platform

          # Pobierz narzędzia
          wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk-tools.zip
          unzip -q sdk-tools.zip -d cmdline-tools
          rm sdk-tools.zip

          # Akceptuj wszystkie licencje
          yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform --licenses

          # Zainstaluj wymagane pakiety
          yes | cmdline-tools/cmdline-tools/bin/sdkmanager --sdk_root=$HOME/.buildozer/android/platform \
            "platform-tools" \
            "platforms;android-31" \
            "build-tools;33.0.2" \
            "ndk;21.4.7075529"

      - name: Build APK
        run: |
          buildozer android debug log_level=2

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: kivy-apk
          path: bin/*.apk
