name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Install system dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          build-essential git zip unzip openjdk-17-jdk \
          python3-pip autoconf libtool pkg-config \
          zlib1g-dev libncurses5 libtinfo5 \
          cmake gradle wget curl

    - name: Install Python deps
      run: |
        python3 -m pip install --upgrade pip setuptools wheel Cython
        pip3 install buildozer==1.5.0

    - name: Install Android SDK & Build Tools
      run: |
        mkdir -p $HOME/.buildozer/android/platform
        cd $HOME/.buildozer/android/platform
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdtools.zip
        unzip -q cmdtools.zip -d cmdline-tools
        rm cmdtools.zip
        mv cmdline-tools $HOME/.buildozer/android/platform/cmdline-tools
        export ANDROID_HOME=$HOME/.buildozer/android/platform
        export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
        yes | $ANDROID_HOME/cmdline-tools/bin/sdkmanager --licenses
        $ANDROID_HOME/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.2"

    - name: Build APK
      run: |
        export ANDROID_HOME=$HOME/.buildozer/android/platform
        export PATH=$ANDROID_HOME/cmdline-tools/bin:$ANDROID_HOME/platform-tools:$PATH
        buildozer android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: kivy-apk
        path: bin/*.apk
