name: Build Kivy APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04   # ważne: zamiast 24.04 używamy 20.04, bo ma paczki potrzebne dla buildozer

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y \
            python3-pip \
            build-essential \
            git \
            zip \
            unzip \
            openjdk-17-jdk \
            autoconf \
            libtool \
            pkg-config \
            zlib1g-dev \
            libncurses5 \
            libtinfo5 \
            cmake

      - name: Install buildozer
        run: |
          pip install --upgrade pip
          pip install cython
          pip install buildozer

      - name: Build APK
        run: |
          cd $GITHUB_WORKSPACE
          buildozer -v android debug

      - name: Upload APK artifact
        uses: actions/upload-artifact@v3
        with:
          name: AABauservice-APK
          path: bin/*.apk
