name: Build Kivy APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest   # zamiast 20.04 – mniej kolejek

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"

    - name: Install system dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y \
          build-essential \
          git \
          openjdk-17-jdk \
          python3-pip \
          python3-setuptools \
          python3-wheel \
          unzip \
          zip \
          autoconf \
          libtool \
          pkg-config \
          zlib1g-dev \
          libncurses5 \
          libtinfo5 \
          libffi-dev \
          cmake \
          ninja-build \
          ccache \
          lld

    - name: Install Buildozer
      run: |
        pip install --upgrade pip wheel setuptools Cython
        pip install buildozer==1.5.0

    - name: Build APK
      run: |
        cd $GITHUB_WORKSPACE
        buildozer -v android debug

    - name: Upload APK artifact
      uses: actions/upload-artifact@v4
      with:
        name: app-apk
        path: bin/*.apk
